name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn install
      - run: yarn build
      - shell: bash
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          npx firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting -m "Commit ${git_hash}"
